[project]
name = "election_maps"
version = "0.1.0"
dependencies = [
    "pyutils @ git+https://github.com/a96tudor/pyutils.git",
    "flask",
    "boto3",
    "flask-cors",
    "certifi",
    "pymongo[srv]",
    "folium"
]


[tool.setuptools]
py-modules = ["election_maps", "scripts"]
